### ISSUE TITLE
ExpoPhaser on Android not working

### ISSUE THREAD

**Issue by NickDelfino** [expo/expo-phaser#2]
Trying to add ExpoPhaser to my Expo Android app and just making a game object causes the app to error. I am using a Galaxy S8. 

`undefined is not an object (evaluating window.emitter.emit`

Not sure what to make of the error. Seems to build okay on the iOS simulator. 

Can provide more details if needed. Thanks for library! Really like the idea!

**Comment by NickDelfino** [comment]
This error changes on second load to:

`EXGL: Invalid pixel data argument for gl.textImage2D()!`

This is all I have in my App.js.

`import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Expo from 'expo';
import ExpoPhaser from 'expo-phaser';

export default class App extends React.Component {
  state = { loading: true };
  async componentWillMount() {
    this.setState({ loading: false });
  }
  render() {
    if (this.state.loading) {
      return <Expo.AppLoading />;
    }

    return (
        <Expo.GLView
            style={{ flex: 1 }}
            onContextCreate={context => startGame({ context })}
        />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

function startGame({ context }) {
  const game = ExpoPhaser.game({ context });
  //
  // game.state.add('Playable', {
  //   preload: function() {
  //     /// This function cannot be async, preload all assets before getting here.
  //     game.load.image(
  //         'man',
  //         Expo.Asset.fromModule(Assets['man.json']).localUri,
  //     );
  //   },
  //   create: function() {},
  //   update: function() {},
  // });
  //
  // game.state.start('Playable');
}`

**Comment by EvanBacon** [comment]
Right, I've tracked the issue down to a problem with base64 image conversion. lol apparently in Android `ImageStore.addImageFromBase64` isn't available. We need an alternative to this in `@expo/browser-polyfill` to proceed.

**Comment by Haipt241** [comment]
Ok, how can we apply fix ?

**Comment by EvanBacon** [comment]
Native code would need to be added to the android build, there is currently no way to parse base64 on Android

**Comment by EvanBacon** [comment]
@axedre nothing definitive right now. I'm working on ARCore for android atm. This is phaser-ce (~2.7) which is a little outdated now. I think it might make sense to add support for the newer versions of Phaser with Android. We still need the `FileSystem`  updates either way. It also might make sense to support a simpler game engine like melon.js as well. If you have any input on any of this lemme know.

**Comment by axedre** [comment]
Nothing much really, apart from a quick SO search (which I'm sure you've already attempted) that yields https://stackoverflow.com/questions/42294821/convert-base64-string-to-image-in-android
I'm no Java developer though so I wouldn't know where to start... :-/

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/pull/2328

**Comment by lobobabysaurus** [comment]
Can a new version be published to npm?  I am getting bit by this issue and the last version published was 10 months ago

**Comment by baochungit** [comment]
How is this going? If it's still not working on Android, please add a note on README so that other people intending to use it for Android app could avoid to take time for this. Thank you!

**Comment by justinTime225** [comment]
I'm also experiencing this error on android, ios works fine.  EXGL: Invalid pixel data argument for gl.texImage2D()!

Here's my code after following https://github.com/expo/expo/pull/2328.  I'm not sure what to do with 'data:image/png;base64'.  Any insight is appreciated! 

    const downloads = [];
    for (let key of Object.keys(Assets)) {
      let asset = Asset.fromModule(Assets[key]);
      await asset.downloadAsync();

      let localUri = asset.localUri;

      if (Platform.OS === 'android') {
        const b64 = await FileSystem.readAsStringAsync(localUri, {
          encoding: FileSystem.EncodingType.Base64,
          // length: 1,
          // position: 0,
        });
        console.log('cache directory: ', FileSystem.cacheDirectory);
        const nextUri = FileSystem.cacheDirectory + 'image.png';
        console.log('nextUri: ', nextUri);
        await FileSystem.writeAsStringAsync(nextUri, b64, {
          encoding: FileSystem.EncodingType.Base64,
        });

        localUri = nextUri;
      }
      downloads.push(localUri);
    }
    this.setState({ loading: false, downloads });

**Comment by angelsinjen** [comment]
Same issue on expo-pixi.
