### ISSUE TITLE
Can this work with pure react native app ?

### ISSUE THREAD

**Issue by im-aditya** [expo/expo-phaser#4]
Can this work by using https://github.com/react-community/react-native-webgl or https://github.com/gre/gl-react-native-v2 so that there won't be any dependency on Expo ?

**Comment by EvanBacon** [comment]
`react-native-webgl` & `gl-react-native` are both outdated standalone versions of Expo.GLView (EXGL). Only EXGL has the necessary functions to handle phaser/pixi. 
It doesn't make much sense for me to maintain those other 2 libraries on top of EXGL. 

[x-post](https://github.com/expo/expo-pixi/issues/30)
[x-post](https://github.com/expo/expo-three/issues/43)

**Comment by im-aditya** [comment]
So currently there is no way to run Phaser/Pixi in a non-Expo based react native project ? Or is there some way we can use EXGL in react native ?

**Comment by EvanBacon** [comment]
coming soon expo will have a more modular system that will allow you to remove unneeded modules. But you would still have to use Expo.

**Comment by im-aditya** [comment]
Ok.. this is actually a bit disappointing as I have tried Expo and it is not currently suitable for our app. I was hoping if I could somehow use this (EXGL) module in my non-expo project to run some ThreeJs and Pixi content.

Anyway, thanks for the quick reply.

**Comment by EvanBacon** [comment]
This library requires GLView, Asset, Font, & FileSystem. All 4 of those are pretty complex core functionality libraries. 
It would be helpful to understand why Expo didn't work for your app. As it stands I have no reason to not use Expo. 
There is still a lot of work to be done to get this library fully functional and it would be a huge burden to extract, and maintain all the necessary components from ExpoKit.

**Comment by im-aditya** [comment]
In my project, along with 3D animations, we are integrating step counter libraries, which we have modified a bit on the native level. Along with that the asset management of Expo (CDN based) is slow for our use case, especially in India where internet connectivity is not that good. Also we need background tasks which are not there in Expo.
